Update pipeline-build-and-deploy-BE.yml

diff --git a/.github/workflows/pipeline-build-and-deploy-BE.yml b/.github/workflows/pipeline-build-and-deploy-BE.yml
--- a/.github/workflows/pipeline-build-and-deploy-BE.yml
+++ b/.github/workflows/pipeline-build-and-deploy-BE.yml
@@ -67,9 +67,9 @@ jobs:
        ssh -i temp_key.pem -o StrictHostKeyChecking=no azureuser@${{ steps.get_ip.outputs.VM_IP }} 'bash -s' << 'ENDSSH'
        if [ -n $(pgrep -f 'java -jar') ]; then kill $(pgrep -f 'java -jar'); fi 
        cd be_expenses_manager
-       nohup java -jar expenses-manager-0.0.1-SNAPSHOT.jar '-Dspring.datasource.username="${{ env.DB_USERNAME }}"' '-Dspring.datasource.password="${{ env.DB_PASSWORD }}"' '-Dspring.datasource.url="${{ env.DB_URL }}"' '-Dazure.document.blob.connectionString="${{ env.REPORTS_ST_SAS_TOKEN_URL }}"' > /dev/null 2>&1 &
+       nohup java  '-Dspring.datasource.username="${{ env.DB_USERNAME }}"' '-Dspring.datasource.password="${{ env.DB_PASSWORD }}"' '-Dspring.datasource.url="${{ env.DB_URL }}"' '-Dazure.document.blob.connectionString="${{ env.REPORTS_ST_SAS_TOKEN_URL }}"' -jar expenses-manager-0.0.1-SNAPSHOT.jar > nohup.out  2>&1 &
        sleep 30
-        if [ -n $(pgrep -f 'java -jar') ]; then echo "Java start successfully" ; fi
+        if [ -n $(pgrep -f 'java -jar') ]; then echo "Java start successfully"; else echo "Java fail to start" && exit 1; fi
        ENDSSH
    
    - name: Clean up temporary key file
