Update pipeline-build-and-deploy-BE.yml

diff --git a/.github/workflows/pipeline-build-and-deploy-BE.yml b/.github/workflows/pipeline-build-and-deploy-BE.yml
--- a/.github/workflows/pipeline-build-and-deploy-BE.yml
+++ b/.github/workflows/pipeline-build-and-deploy-BE.yml
@@ -67,7 +67,7 @@ jobs:
        if [ -n $(pgrep -f 'java -jar') ]; then kill $(pgrep -f 'java -jar'); fi 
        cd be_expenses_manager
        nohup java -jar expenses-manager-0.0.1-SNAPSHOT.jar &
-       if [ ps -p $($! > /dev/null) ]; then echo "Java start successfully." && exit 0; else echo "Error at start Java." && exit 1; fi
+       if  ps -p $($! > /dev/null) ; then echo "Java start successfully." && exit 0; else echo "Error at start Java." && exit 1; fi
        ENDSSH
    
    - name: Clean up temporary key file
